### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by UVJkiNTQ** [deadblue/cli115#1]
-depth 1 cannot be processed by Linux Shell.
`
find: warning: you have specified the global option -depth after the argument -type, but global options are not positional, i.e., -depth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: paths must precede expression: '1' 
`
I correct it with -mindepth 1 -maxdepth 1

I tried command `./cli115`
After login with scanning, error occurs.
`
panic: runtime error: invalid memory address or nil pointer dereference                                                               [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6f53ec]                                                               goroutine 1 [running]:                                             go.dead.blue/cli115/internal/app/context.(*Impl).Startup(0xc0000cc4c0, 0xa8ed40, 0x7aa4ad)                                                    /home/aaa/115/cli115/internal/app/context/context.go:47 +0x10c                                                               go.dead.blue/cli115/internal/pkg/terminal.(*Terminal).Run(0xc0000a6460, 0xc0000f7eb8, 0xa)
        /home/aaa/115/cli115/internal/pkg/terminal/terminal.go:34 +0x3b
go.dead.blue/cli115/internal/app.Run(0x0, 0xc00008e058)
        /home/aaa/115/cli115/internal/app/app.go:39 +0x697
main.main()
        /home/aaa/115/cli115/cmd/cli115/main.go:8 +0x22
`
Is there anything wrong with the building?

BTW, is there any reference for the instructions (upload/move/del,etc)?

**Comment by deadblue** [comment]
Thank you, I haven't test Makefile on Linux, I will fix it later.

This project is still work in process, so I don't start to write manual for it.😅

**Comment by deadblue** [comment]
Hello.
I have fixed the Makefile with your advice, thank you.

For the error after login, it occured when cli115 can't find `aria2` in your system.
I can reproduce this error, and have fixed it in commit 06ea65a.

About the manual, I will start it soon🕊.
